import { Color, FontFamily } from "../../Styles/StylesCT";
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    groupIconLayout: {
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    groupLayout2: {
      height: 55,
      width: 303,
      position: "absolute",
    },
    groupPosition3: {
      top: 0,
      left: 0,
    },
    groupChildShadowBox1: {
      backgroundColor: Color.gredient,
      shadowOpacity: 1,
      elevation: 14.95,
      shadowRadius: 14.95,
      shadowOffset: {
        width: 10.1,
        height: 15.5,
      },
      shadowColor: "rgba(226, 226, 226, 0.25)",
      borderRadius: 45,
      top: 0,
      left: 0,
    },
    createTypo: {
      color: Color.colorWhite,
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
    },
    nameTypo: {
      fontSize: 13,
      fontFamily: FontFamily.poppinsRegular,
      textAlign: "left",
      color: Color.colorWhite,
      left: "0%",
      position: "absolute",
    },
    timeTypo: {
      color: Color.colorLightsteelblue,
      fontFamily: FontFamily.poppinsRegular,
      fontSize: 13,
      textAlign: "left",
      position: "absolute",
    },
    oct242023Typo: {
      fontSize: 19,
      textAlign: "left",
      color: Color.colorWhite,
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
      left: "0%",
      position: "absolute",
    },
    pmTypo: {
      top: "50.47%",
      color: Color.colorDarkslategray,
      fontSize: 19,
      textAlign: "left",
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
      position: "absolute",
    },
    createTypo1: {
      fontSize: 14,
      position: "absolute",
    },
    groupLayout1: {
      opacity: 0.5,
      height: 1,
      width: 306,
      position: "absolute",
    },
    groupChildLayout: {
      height: 1,
      width: 306,
      position: "absolute",
    },
    groupLayout: {
      height: 42,
      width: 93,
      position: "absolute",
    },
    quizPosition: {
      fontSize: 10,
      top: "32.86%",
      position: "absolute",
    },
    groupPosition1: {
      left: 134,
      height: 42,
      width: 93,
      position: "absolute",
    },
    groupPosition: {
      left: 237,
      height: 42,
      width: 93,
      position: "absolute",
    },
    groupIcon: {
      height: "99.99%",
      width: "100.08%",
      right: "-0.08%",
      bottom: "0.01%",
      left: "0%",
      top: "0%",
    },
    groupIcon1: {
      height: "75.04%",
      width: "141.59%",
      right: "-41.59%",
      bottom: "24.96%",
      left: "0%",
      top: "0%",
    },
    vectorIcon: {
      height: "11.81%",
      width: "85.28%",
      top: "124.48%",
      right: "19.22%",
      bottom: "-36.29%",
      left: "-4.5%",
    },
    createATaskChild: {
      top: 734,
      left: 36,
      width: 296,
      height: 33,
      position: "absolute",
    },
    createATaskItem: {
      top: "35%",
      width: "100%",
      height: "65%",
      left: 0,
      position: "absolute",
    },
    groupChild: {
      height: 55,
      width: 303,
      position: "absolute",
    },
    createTask: {
      top: "30.43%",
      left: "35.5%",
      textAlign: "left",
      fontSize: 14,
      position: "absolute",
    },
    groupInner: {
      height: 55,
      width: 303,
      position: "absolute",
    },
    group: {
      top: 715,
      left: 33,
    },
    createATaskInner: {
      height: "3.01%",
      width: "6.29%",
      top: "4.48%",
      right: "8.59%",
      bottom: "92.5%",
      left: "85.11%",
    },
    arrowShortLeft: {
      top: 35,
      left: 27,
      width: 26,
      height: 26,
      position: "absolute",
      overflow: "hidden",
    },
    createATask1: {
      textAlign: "center",
      fontSize: 14,
      position: "absolute",
      left: "0%",
      top: "0%",
    },
    group1: {
      height: "2.75%",
      width: "27.33%",
      top: "4.71%",
      right: "38.69%",
      bottom: "92.54%",
      left: "33.98%",
      position: "absolute",
    },
    name: {
      fontFamily: FontFamily.poppinsRegular,
      top: "0%",
    },
    startTime: {
      left: "0.19%",
      top: "44.21%",
      color: Color.colorLightsteelblue,
    },
    endTime: {
      left: "44.16%",
      top: "44.21%",
      color: Color.colorLightsteelblue,
    },
    date: {
      top: "17.28%",
      fontFamily: FontFamily.poppinsRegular,
    },
    description: {
      top: "64.5%",
      left: "0%",
    },
    category: {
      top: "95.81%",
      left: "0.19%",
    },
    operatingSystemsProject: {
      top: "6.26%",
    },
    pm: {
      color: Color.colorDarkslategray,
      left: "0.19%",
    },
    pm1: {
      left: "41.44%",
      color: Color.colorDarkslategray,
    },
    oct242023: {
      top: "23.55%",
    },
    loremIpsumDolor: {
      top: "70.76%",
      fontWeight: "500",
      fontFamily: FontFamily.poppinsMedium,
      color: Color.colorDarkslategray,
      textAlign: "left",
      left: "0%",
      width: "100%",
    },
    groupItem: {
      top: 68,
      left: 1,
    },
    groupChild1: {
      top: 284,
      left: 1,
    },
    groupChild2: {
      top: 150,
      left: 0,
    },
    groupChild3: {
      top: 438,
      left: 0,
    },
    nameParent: {
      height: "59.67%",
      width: "83.17%",
      top: "12.18%",
      right: "8.41%",
      bottom: "28.14%",
      left: "8.41%",
      position: "absolute",
    },
    rectangleLineargradient: {
      backgroundColor: Color.gredient,
      shadowOpacity: 1,
      elevation: 14.95,
      shadowRadius: 14.95,
      shadowOffset: {
        width: 10,
        height: 15,
      },
      shadowColor: "rgba(226, 226, 226, 0.25)",
      borderRadius: 45,
      top: 0,
      left: 0,
    },
    quiz: {
      left: "38.46%",
      textAlign: "center",
      color: Color.colorWhite,
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
    },
    rectangleGroup: {
      top: 0,
      left: 0,
    },
    group2: {
      left: 31,
      width: 93,
      top: 591,
    },
    groupChildShadowBox: {
      backgroundColor: Color.colorLavender,
      height: 42,
      width: 93,
      shadowOpacity: 1,
      elevation: 14.95,
      shadowRadius: 14.95,
      shadowOffset: {
        width: 10,
        height: 15,
      },
      shadowColor: "rgba(226, 226, 226, 0.25)",
      borderRadius: 45,
      top: 0,
      left: 0,
      position: "absolute",
    },
    courseProject: {
      left: "12.82%",
      color: Color.colorDarkslategray,
      fontFamily: FontFamily.poppinsRegular,
      textAlign: "center",
    },
    group3: {
      top: 645,
      left: 31,
      width: 93,
    },
    presentation: {
      width: "72.44%",
      left: "21.8%",
      color: Color.colorDarkslategray,
      fontFamily: FontFamily.poppinsRegular,
      textAlign: "left",
    },
    group4: {
      top: 591,
    },
    classActivity: {
      width: "84.62%",
      left: "15.38%",
      color: Color.colorDarkslategray,
      fontFamily: FontFamily.poppinsRegular,
      textAlign: "left",
    },
    group5: {
      top: 645,
    },
    assignment: {
      left: "19.23%",
      color: Color.colorDarkslategray,
      fontFamily: FontFamily.poppinsRegular,
      textAlign: "center",
    },
    group6: {
      top: 591,
    },
    others: {
      left: "25%",
      color: Color.colorDarkslategray,
      fontFamily: FontFamily.poppinsRegular,
      textAlign: "left",
    },
    group7: {
      top: 645,
    },
    createATask: {
      backgroundColor: Color.colorWhite,
      flex: 1,
      height: 800,
      overflow: "hidden",
      width: "100%",
    },
  });

  export default styles;