import { StyleSheet } from "react-native";
import { Color, FontFamily } from "../../Styles/StylesHome";


const styles = StyleSheet.create({
  ProfileEdit: {
    top: "91%",
    left: 39,
    width: 293,
    height: 35,
    position: "absolute",
  },
  NotificationsTab: {
    top: "91%",
    left: "29%",
    width: 293,
    height: 35,
    position: "absolute",
  },
  CreateTask: {
    top: "91%",
    left: "51%",
    width: 293,
    height: 35,
    position: "absolute",
  },
  TaskCalendar: {
    top: "91%",
    left: "73%",
    width: 293,
    height: 35,
    position: "absolute",
  },
    iconCardLayout: {
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    textFlexBox: {
      textAlign: "left",
      color: Color.colorDarkslategray,
      position: "absolute",
    },
    cardLayout1: {
      height: 203,
      width: 204,
      top: 240,
      position: "absolute",
    },
    groupChildPosition: {
      bottom: "0%",
      left: "0%",
      top: "0%",
      height: "100%",
    },
    card1Position: {
      left: "-7.04%",
      bottom: "-10.62%",
      top: "-3.49%",
      height: "114.11%",
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    text1Clr: {
      color: Color.colorWhite,
      textAlign: "left",
      position: "absolute",
    },
    project1Typo: {
      fontSize: 13,
      left: "0%",
      top: "0%",
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
    },
    groupPosition4: {
      height: 42,
      top: 179,
      position: "absolute",
    },
    groupPosition3: {
      left: 0,
      top: 0,
      height: 42,
      width: 93,
    },
    groupChildShadowBox1: {
      elevation: 14.95,
      shadowRadius: 14.95,
      shadowColor: "rgba(226, 226, 226, 0.25)",
      backgroundColor: Color.colorWhite,
      borderRadius: 45,
      position: "absolute",
      shadowOpacity: 1,
      shadowOffset: {
        width: 0,
        height: 2.3918025493621826,
      },
    },
    tasksTypo: {
      fontSize: 10,
      top: "32.86%",
    },
    groupChildShadowBox: {
      backgroundColor: Color.colorLavender_100,
      elevation: 14.95,
      shadowRadius: 14.95,
      shadowColor: "rgba(226, 226, 226, 0.25)",
      borderRadius: 45,
      position: "absolute",
      shadowOpacity: 1,
      shadowOffset: {
        width: 0,
        height: 2.3918025493621826,
      },
    },
    completedPosition: {
      left: "20.51%",
      fontSize: 10,
      top: "32.86%",
      fontFamily: FontFamily.poppinsRegular,
    },
    groupPosition2: {
      width: "31.2%",
      bottom: "0%",
      top: "0%",
      height: "100%",
      position: "absolute",
    },
    myTasks1Clr: {
      color: Color.colorGray,
      textAlign: "left",
      position: "absolute",
    },
    homeLayout: {
      width: 6,
      backgroundColor: Color.colorLavender_200,
      height: 6,
      borderRadius: 47,
      top: 460,
      position: "absolute",
    },
    cardLayout: {
      height: 73,
      width: 340,
      left: 32,
      position: "absolute",
    },
    groupPosition1: {
      left: "6.18%",
      bottom: "25.44%",
      top: "24.59%",
      height: "49.97%",
      position: "absolute",
    },
    list1Position: {
      bottom: "26.18%",
      top: "24.61%",
      height: "49.21%",
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    groupPosition: {
      bottom: "4.98%",
      height: "95.02%",
      right: "0%",
      top: "0%",
      position: "absolute",
    },
    daysPosition: {
      color: Color.colorDarkgray,
      top: "56.96%",
      height: "43.04%",
      fontSize: 10,
      left: "0%",
      fontFamily: FontFamily.poppinsRegular,
      textAlign: "left",
      position: "absolute",
    },
    groupIcon: {
      height: "3.06%",
      width: "81.87%",
      top: "4.41%",
      right: "9.62%",
      bottom: "92.53%",
      left: "8.51%",
    },
    text: {
      marginTop: -350.1,
      left: "8.25%",
      fontSize: 28,
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
      top: "50%",
      color: Color.colorDarkslategray,
    },
    currentBalance: {
      marginTop: -305,
      width: "30.88%",
      fontSize: 14,
      height: 20,
      opacity: 0.54,
      fontFamily: FontFamily.poppinsRegular,
      left: "8.08%",
      textAlign: "left",
      color: Color.colorDarkslategray,
      top: "50%",
      position: "absolute",
    },
    card1bg: {
      height: "99.81%",
      bottom: "0.19%",
      backgroundColor: "transparent",
      borderRadius: 12,
      left: "0%",
      right: "0%",
      top: "0%",
      position: "absolute",
      width: "100%",
    },
    card1Mask: {
      width: "114.08%",
      right: "-7.04%",
    },
    text1: {
      width: "79.77%",
      top: "37.17%",
      fontSize: 20,
      lineHeight: 25,
      left: "10.85%",
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
    },
    card1bgParent: {
      left: "0%",
      right: "0%",
      position: "absolute",
      width: "100%",
    },
    currentBalance1: {
      top: "80.24%",
      fontSize: 12,
      fontWeight: "300",
      fontFamily: FontFamily.poppinsLight,
      left: "10.85%",
    },
    project1: {
      color: Color.colorWhite,
      textAlign: "left",
      position: "absolute",
      height: "100%",
      fontSize: 13,
      width: "100%",
    },
    group: {
      height: "10.03%",
      width: "59.53%",
      top: "13.86%",
      right: "9.38%",
      bottom: "76.11%",
      left: "31.09%",
      position: "absolute",
    },
    cardChild: {
      height: "15.03%",
      width: "14.94%",
      top: "10.91%",
      right: "74.21%",
      bottom: "74.05%",
      left: "10.85%",
    },
    card: {
      left: 30,
    },
    card1Mask1: {
      right: "7.04%",
      width: "100%",
    },
    cardDisabled: {
      left: 248,
      opacity: 0.5,
    },
    groupChild: {
      left: 0,
      top: 0,
      height: 42,
      width: 93,
    },
    myTasks: {
      left: "28.21%",
      fontSize: 10,
      top: "32.86%",
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
      textAlign: "left",
      color: Color.colorDarkslategray,
      position: "absolute",
    },
    rectangleParent: {
      position: "absolute",
    },
    group4: {
      width: 93,
      height: 42,
      top: 179,
      left: 30,
    },
    groupItem: {
      left: 0,
      top: 0,
      height: 42,
      width: 93,
    },
    inprogress: {
      left: "22.44%",
      fontSize: 10,
      top: "32.86%",
      fontFamily: FontFamily.poppinsRegular,
      textAlign: "left",
      color: Color.colorDarkslategray,
      position: "absolute",
    },
    group5: {
      left: 133,
      width: 93,
      height: 42,
      top: 179,
    },
    groupInner: {
      left: 0,
      top: 0,
      height: 42,
      width: 93,
    },
    completed: {
      textAlign: "left",
      color: Color.colorDarkslategray,
      position: "absolute",
    },
    group6: {
      left: 236,
      width: 93,
      height: 42,
      top: 179,
    },
    rectangleView: {
      left: "0%",
      bottom: "0%",
      top: "0%",
      height: "100%",
      right: "0%",
      width: "100%",
    },
    myTasks1: {
      fontSize: 10,
      top: "32.86%",
      left: "28.21%",
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
    },
    group7: {
      right: "68.8%",
      left: "0%",
    },
    groupChild1: {
      left: "0%",
      bottom: "0%",
      top: "0%",
      height: "100%",
      right: "0%",
      width: "100%",
    },
    inProgress: {
      left: "19.87%",
      fontSize: 10,
      top: "32.86%",
      fontFamily: FontFamily.poppinsRegular,
    },
    group8: {
      right: "34.4%",
      left: "34.4%",
    },
    groupChild2: {
      left: "0%",
      bottom: "0%",
      top: "0%",
      height: "100%",
      right: "0%",
      width: "100%",
    },
    completed1: {
      left: "20.51%",
      fontSize: 10,
      top: "32.86%",
      fontFamily: FontFamily.poppinsRegular,
    },
    group9: {
      left: "68.8%",
      right: "0%",
    },
    label: {
      width: 299,
      height: 42,
      top: 179,
      left: 30,
    },
    progress: {
      top: "60%",
      fontSize: 19,
      left: "8.08%",
      textAlign: "left",
      color: Color.colorDarkslategray,
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
      position: "absolute",
    },
    homeChild: {
      left: 161,
      width: 25,
      height: 6,
      borderRadius: 47,
      top: 460,
      backgroundColor: "transparent",
      position: "absolute",
    },
    homeItem: {
      left: 191,
    },
    homeInner: {
      left: 202,
    },
    vectorIcon: {
      height: "11.81%",
      width: "85.21%",
      top: "124.49%",
      right: "19.21%",
      bottom: "-36.3%",
      left: "-4.41%",
    },
    cardShadowBox: {
      elevation: 13.75,
      shadowRadius: 13.75,
      shadowColor: "rgba(0, 0, 0, 0.02)",
      backgroundColor: Color.colorWhite,
      borderRadius: 12,
      left: "0%",
      bottom: "0%",
      right: "0%",
      top: "0%",
      height: "100%",
      position: "absolute",
      width: "100%",
      shadowOpacity: 1,
      shadowOffset: {
        width: 0,
        height: 2,
      },
    },
    vectorIcon1: {
      width: "25.77%",
      right: "74.23%",
      left: "0%",
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    toDoList1Traced: {
      width: "10.57%",
      right: "81.82%",
      left: "7.61%",
    },
    designChanges: {
      fontSize: 13,
      left: "0%",
      top: "0%",
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
    },
    group12: {
      height: "57.75%",
      bottom: "42.25%",
      left: "0%",
      right: "0%",
      top: "0%",
      position: "absolute",
      width: "100%",
    },
    daysAgo: {
      width: "91.84%",
    },
    group11: {
      width: "63.64%",
      left: "36.36%",
    },
    group10: {
      width: "45.66%",
      right: "48.16%",
    },
    cardMediumItem: {
      height: "23.59%",
      width: "1.35%",
      top: "38.52%",
      right: "6.37%",
      bottom: "37.89%",
      left: "92.28%",
    },
    cardMedium: {
      top: 540,
    },
    vectorIcon2: {
      width: "19.14%",
      right: "80.86%",
      left: "0%",
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    toDoList1Traced1: {
      width: "7.85%",
      right: "86.5%",
      left: "5.65%",
    },
    daysAgo1: {
      width: "59.47%",
    },
    group14: {
      width: "73%",
      left: "27%",
    },
    group13: {
      width: "61.48%",
      right: "32.34%",
    },
    cardMedium1: {
      top: 630,
    },
    homeChild1: {
      top: 661,
      left: 318,
      width: 4,
      height: 17,
      position: "absolute",
    },
    home: {
      backgroundColor: "#f2f5ff",
      shadowColor: "rgba(0, 0, 0, 0.25)",
      shadowRadius: 2.39,
      elevation: 2.39,
      flex: 1,
      height: 800,
      overflow: "hidden",
      shadowOpacity: 1,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      width: "100%",
    },
  });

  export default styles;