import { StyleSheet } from "react-native";
import { Color, FontFamily, FontSize } from "../../Styles/StylesNoti";


const styles = StyleSheet.create({
    groupIconLayout: {
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    cardLayout: {
      height: 73,
      width: 310,
      left: 31,
      position: "absolute",
    },
    groupPosition1: {
      left: "6.18%",
      bottom: "25.44%",
      top: "24.59%",
      height: "49.97%",
      position: "absolute",
    },
    list1Position: {
      bottom: "26.18%",
      top: "24.61%",
      height: "49.21%",
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    groupPosition: {
      bottom: "4.98%",
      height: "95.02%",
      right: "0%",
      top: "0%",
      position: "absolute",
    },
    groupIconPosition: {
      left: "0%",
      top: "0%",
    },
    designTypo: {
      textAlign: "left",
      color: Color.colorGray,
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
      left: "0%",
      top: "0%",
      position: "absolute",
    },
    daysTypo: {
      color: Color.colorDarkgray,
      fontFamily: FontFamily.poppinsRegular,
      fontSize: 10,
      top: "56.96%",
      height: "43.04%",
      textAlign: "left",
      left: "0%",
      position: "absolute",
    },
    groupIcon: {
      left: "0%",
      top: "0%",
      bottom: "0%",
      height: "100%",
      maxWidth: "100%",
      right: "0%",
      width: "100%",
    },
    groupIcon1: {
      height: "109.95%",
      width: "110.11%",
      right: "-10.11%",
      bottom: "-9.95%",
      left: "0%",
      top: "0%",
    },
    vectorIcon: {
      height: "11.81%",
      width: "85.21%",
      top: "124.49%",
      right: "19.21%",
      bottom: "-36.3%",
      left: "-4.41%",
    },
    notificationsTabChild: {
      top: "91%",
      left: 39,
      width: 293,
      height: 35,
      position: "absolute",
    },
    notificationsTabItem: {
      top: 0,
      left: 0,
      width: "100%",
      height: "23%",
      borderRadius: 10,
      position: "absolute",
    },
    notificationsTabInner: {
     /* height: "3.01%",
      width: "6.29%",
      top: "4.48%",
      right: "8.67%",
      bottom: "92.5%",
      left: "85.04%",*/
      justifyContent:"center"
    },
    notifications: {
      height: "5.5%",
      width: "51.37%",
      top: "9.63%",
      left: "26.23%",
      fontSize: 25,
      color: "#f2f4f6",
      textAlign: "center",
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
      position: "absolute",
    },
    cardChildShadowBox: {
      shadowOpacity: 1,
      elevation: 13.75,
      shadowRadius: 13.75,
      shadowOffset: {
        width: 0,
        height: -4.185654640197754,
      },
      shadowColor: "rgba(0, 0, 0, 0.02)",
      backgroundColor: Color.colorWhite,
      borderRadius: 12,
      left: "0%",
      bottom: "0%",
      right: "0%",
      top: "0%",
      height: "100%",
      position: "absolute",
      width: "100%",
    },
    vectorIcon1: {
      width: "18.75%",
      right: "81.25%",
      left: "0%",
      top: "0%",
      bottom: "0%",
      height: "100%",
      maxWidth: "100%",
    },
    toDoList1Traced: {
      width: "7.69%",
      right: "86.78%",
      left: "5.54%",
    },
    designChanges: {
      fontSize: FontSize.size_xs,
    },
    group2: {
      height: "51.97%",
      bottom: "48.03%",
      right: "0%",
      width: "100%",
      top: "0%",
      left: "0%",
      position: "absolute",
    },
    daysAgo: {
      width: "57.8%",
    },
    group1: {
      width: "73.55%",
      left: "26.45%",
    },
    group: {
      width: "70.77%",
      right: "32.05%",
    },
    cardMediumItem: {
      height: "23.59%",
      width: "1.35%",
      top: "38.52%",
      right: "6.37%",
      bottom: "37.89%",
      left: "92.28%",
    },
    cardMedium: {
      top: 192,
    },
    vectorIcon2: {
      width: "14.5%",
      right: "85.5%",
      left: "0%",
      top: "0%",
      bottom: "0%",
      height: "100%",
      maxWidth: "100%",
    },
    toDoList1Traced1: {
      width: "5.95%",
      right: "89.77%",
      left: "4.28%",
    },
    daysAgo1: {
      width: "41.33%",
    },
    group4: {
      width: "79.55%",
      left: "20.45%",
    },
    group3: {
      width: "83.17%",
      right: "12.65%",
    },
    cardMedium1: {
      top: 354,
    },
    vectorIcon3: {
      width: "13.94%",
      right: "86.06%",
      left: "0%",
      top: "0%",
      bottom: "0%",
      height: "100%",
      maxWidth: "100%",
    },
    toDoList1Traced2: {
      width: "5.72%",
      right: "90.16%",
      left: "4.12%",
    },
    daysAgo2: {
      width: "39.36%",
    },
    group7: {
      width: "80.33%",
      left: "19.67%",
    },
    group6: {
      width: "87.4%",
      right: "9.42%",
    },
    cardMedium2: {
      top: 273,
    },
    vectorIcon4: {
      width: "15.89%",
      right: "84.11%",
      left: "0%",
      top: "0%",
      bottom: "0%",
      height: "100%",
      maxWidth: "100%",
    },
    toDoList1Traced3: {
      width: "6.52%",
      right: "88.79%",
      left: "4.69%",
    },
    designChanges3: {
      fontSize: 13,
    },
    group11: {
      height: "57.75%",
      bottom: "42.25%",
      right: "0%",
      width: "100%",
      top: "0%",
      left: "0%",
      position: "absolute",
    },
    daysAgo3: {
      width: "46.44%",
    },
    group10: {
      width: "77.59%",
      left: "22.41%",
    },
    group9: {
      width: "74.07%",
      right: "19.75%",
    },
    cardMedium3: {
      top: 435,
    },
    arrowShortLeft: {
      top: 35,
      left: 27,
      width: 26,
      height: 26,
      position: "absolute",
      overflow: "hidden",
    },
    notificationsTab: {
      backgroundColor: Color.colorGray,
      flex: 1,
      height: "100%",
      overflow: "hidden",
      width: "100%",
    },
  });

  export default styles;