import { StyleSheet } from "react-native";
import { Color, FontFamily } from "../../Styles/StylesProfile";

const styles = StyleSheet.create({
  notificationsTabChild: {
    top: "91%",
    left: 39,
    width: 293,
    height: 35,
    position: "absolute",
  },
    rectangleLayout: {
      height: 38,
      position: "absolute",
      padding: 10,
    },
    phoneTypo: {
      textAlign: "left",
      color: Color.colorBlack,
      fontFamily: FontFamily.poppinsMedium,
      fontWeight: "500",
      fontSize: 13,
      left: 34,
      position: "absolute",
    },
    updateTypo: {
      color: Color.colorWhite,
      fontSize: 14,
      textAlign: "left",
      position: "absolute",
    },
    textTypo: {
      fontFamily: FontFamily.poppinsRegular,
      fontSize: 12,
      textAlign: "left",
      color: Color.colorBlack,
      position: "absolute",
    },
    profileEditChild: {
      top: 0,
      left: 0,
      width: "100%",
      height: "23%",
      backgroundColor: "transparent",
      position: "absolute",
    },
    unsplashjmurdhtm7ngIcon: {
      top: 111,
      left: 118,
      width: 135,
      height: 135,
      position: "absolute",
    },
    profileEditItem: {
      top: 304,
      width: 301,
      borderWidth: 0.9,
      borderColor: Color.colorDarkgray,
      borderStyle: "solid",
      backgroundColor: Color.colorSilver,
      borderRadius: 8,
      left: 34,
      height: 38,
    },
    profileEditInner: {
      top: 382,
      width: 301,
      borderWidth: 0.9,
      borderColor: Color.colorDarkgray,
      borderStyle: "solid",
      backgroundColor: Color.colorSilver,
      borderRadius: 8,
      left: 34,
      height: 38,
    },
    rectangleView: {
      top: 460,
      width: 301,
      borderWidth: 0.9,
      borderColor: Color.colorDarkgray,
      borderStyle: "solid",
      backgroundColor: Color.colorSilver,
      borderRadius: 8,
      left: 34,
      height: 38,
    },
    profileEditChild1: {
      top: 537,
      width: 301,
      borderWidth: 0.9,
      borderColor: Color.colorDarkgray,
      borderStyle: "solid",
      backgroundColor: Color.colorSilver,
      borderRadius: 8,
      left: 34,
      height: 38,
    },
    username: {
      top: 282,
    },
    editProfile: {
      top: 51,
      left: 147,
      fontWeight: "600",
      fontFamily: FontFamily.poppinsSemiBold,
    },
    phoneNumber: {
      top: 438,
      display: "none",
    },
    emailId: {
      top: 360,
    },
    phoneNumber1: {
      top: 435,
    },
    password: {
      top: 516,
    },
    rectangleLineargradient: {
      top: 637,
      left: 51,
      borderRadius: 9,
      width: 268,
      backgroundColor: "transparent",
    },
    update: {
      top: 646,
      left: 158,
      fontWeight: "700",
      fontFamily: FontFamily.poppinsBold,
    },
    usman: {
      top: 315,
      left: 46,
      fontSize: 11,
    },
    changePicture: {
      top: 246,
      left: 141,
    },
    usmangmailcom: {
      top: 391,
      left: 46,
      fontSize: 11,
    },
    text: {
      top: 470,
      left: 46,
      fontSize: 11,
    },
    text1: {
      top: 548,
      left: 46,
      fontSize: 11,
    },
    arrowLeftIcon: {
      top: 47,
      left: 16,
      width: 25,
      height: 28,
      position: "absolute",
    },
    ushareAltIcon: {
      top: 45,
      left: 332,
      width: 20,
      height: 20,
      position: "absolute",
      overflow: "hidden",
    },
    profileEdit: {
      backgroundColor: Color.colorWhite,
      flex: 1,
      width: "100%",
      height: "100%",
      overflow: "hidden",
    },
  });

  export default styles;