import { StyleSheet } from "react-native";
import { FontFamily, Color } from "../../Styles/StylesTC";

const styles = StyleSheet.create({
  notificationsTabChild: {
    top: "91%",
    left: 39,
    width: 293,
    height: 35,
    position: "absolute",
  },
    groupIconLayout: {
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    groupChildShadowBox: {
      shadowOpacity: 1,
      shadowOffset: {
        width: 0,
        height: 2,
      },
    },
    moTypo: {
      textAlign: "left",
      fontFamily: FontFamily.poppinsMedium,
      fontWeight: "500",
      fontSize: 14,
      top: "23.72%",
      height: "29.79%",
      color: Color.colorDarkslategray,
      position: "absolute",
    },
    tuTypo: {
      width: "5.38%",
      textAlign: "left",
      fontFamily: FontFamily.poppinsMedium,
      fontWeight: "500",
      fontSize: 14,
      top: "23.72%",
      height: "29.79%",
      position: "absolute",
    },
    saTypo: {
      width: "6.14%",
      textAlign: "left",
      color: Color.colorDarkslategray,
      fontFamily: FontFamily.poppinsMedium,
      fontWeight: "500",
      fontSize: 14,
      top: "23.72%",
      height: "29.79%",
      position: "absolute",
    },
    textTypo: {
      fontFamily: FontFamily.poppinsLight,
      fontWeight: "300",
      top: "51.27%",
      width: "3.07%",
      textAlign: "left",
      fontSize: 14,
      height: "29.79%",
      position: "absolute",
    },
    text7Typo: {
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
      textAlign: "left",
      position: "absolute",
    },
    groupPosition3: {
      top: 0,
      height: 42,
      width: 102,
      left: "8%",
      position: "absolute",
    },
    cardLayout: {
      height: "9.1%",
      width: "88%",
      left: "5%",
      position: "absolute",
    },
    groupPosition2: {
      left: "6.18%",
      bottom: "25.44%",
      top: "24.59%",
      height: "49.97%",
      position: "absolute",
    },
    list1Position: {
      bottom: "26.18%",
      top: "24.61%",
      height: "49.21%",
      maxHeight: "100%",
      maxWidth: "100%",
      position: "absolute",
      overflow: "hidden",
    },
    groupPosition1: {
      bottom: "4.98%",
      height: "95.02%",
      right: "0%",
      top: "0%",
      position: "absolute",
    },
    groupPosition: {
      bottom: "42.25%",
      height: "57.75%",
      left: "0%",
      top: "0%",
      position: "absolute",
    },
    daysTypo: {
      color: Color.colorDarkgray,
      fontFamily: FontFamily.poppinsRegular,
      top: "56.96%",
      height: "43.04%",
      fontSize: 10,
      textAlign: "left",
      left: "0%",
      position: "absolute",
    },
    groupIcon: {
      left: "0%",
      bottom: "0%",
      height: "100%",
      maxWidth: "100%",
      top: "0%",
      right: "0%",
      width: "100%",
    },
    groupIcon1: {
      height: "109.95%",
      width: "110.11%",
      right: "-10.11%",
      bottom: "-9.95%",
      left: "0%",
      top: "0%",
    },
    vectorIcon: {
      height: "11.81%",
      width: "85.21%",
      top: "124.49%",
      right: "19.21%",
      bottom: "-36.3%",
      left: "-4.41%",
    },
    taskCalenderChild: {
      top: 734,
      left: 39,
      width: 293,
      height: 35,
      position: "absolute",
    },
    taskCalenderItem: {
      top: -22,
      shadowColor: "rgba(114, 92, 193, 0.15)",
      shadowRadius: 26.31,
      elevation: 26.31,
      width: "100%",
      height: 295,
      backgroundColor: Color.colorWhite,
      borderRadius: 12,
      left: 0,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      position: "absolute",
    },
    taskCalenderInner: {
      height: "3.01%",
      width: "6.29%",
      top: "4.48%",
      right: "8.67%",
      bottom: "92.5%",
      left: "85.04%",
    },
    vectorIcon1: {
      width: "16.03%",
      right: "73.03%",
      left: "10.94%",
      opacity: 0.1,
      bottom: "0%",
      height: "100%",
      maxWidth: "100%",
      top: "0%",
    },
    mo: {
      width: "6.91%",
      left: "0%",
    },
    tu: {
      left: "16.2%",
    },
    we: {
      width: "7.68%",
      left: "31.07%",
    },
    th: {
      left: "47.25%",
      color: Color.colorDarkslategray,
    },
    fr: {
      width: "4.61%",
      left: "63.3%",
    },
    sa: {
      left: "78.48%",
    },
    su: {
      left: "93.86%",
    },
    text: {
      left: "1.84%",
      color: Color.colorDarkslategray,
    },
    text1: {
      left: "17.37%",
    },
    text2: {
      left: "32.9%",
      color: Color.colorDarkslategray,
    },
    text3: {
      left: "48.43%",
      color: Color.colorDarkslategray,
    },
    text4: {
      left: "63.96%",
      color: Color.colorDarkslategray,
    },
    text5: {
      left: "79.49%",
      color: Color.colorDarkslategray,
    },
    text6: {
      left: "95.02%",
      color: Color.colorDarkslategray,
    },
    group: {
      height: "9.19%",
      width: "85.73%",
      top: "21.23%",
      right: "7%",
      bottom: "69.58%",
      left: "7.28%",
      position: "absolute",
    },
    text7: {
      marginTop: -308.51,
      top: "50%",
      fontSize: 28,
      color: Color.colorDarkslategray,
      left: "7.28%",
    },
    groupChild: {
      borderRadius: 45,
      shadowColor: "rgba(226, 226, 226, 0.25)",
      shadowRadius: 14.95,
      elevation: 14.95,
      backgroundColor: "transparent",
      shadowOpacity: 1,
      shadowOffset: {
        width: 0,
        height: 2.3,
      },
    },
    addTask: {
      top: "32.86%",
      left: "36.84%",
      color: Color.colorWhite,
      fontSize: 10,
      fontFamily: FontFamily.poppinsSemiBold,
      fontWeight: "600",
      textAlign: "left",
      position: "absolute",
    },
    addIcon: {
      top: 14,
      left: 19,
      width: 14,
      height: 14,
      position: "absolute",
      overflow: "hidden",
    },
    group1: {
      top: 91,
      left: 236,
      height: 42,
      width: 102,
      position: "absolute",
    },
    tasks: {
      top: "38.12%",
      left: "7.92%",
      fontSize: 19,
      color: Color.colorDarkslategray,
    },
    cardChildShadowBox: {
      elevation: 13.75,
      shadowRadius: 13.75,
      shadowColor: "rgba(0, 0, 0, 0.02)",
      shadowOpacity: 1,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      backgroundColor: Color.colorWhite,
      borderRadius: 12,
      left: "0%",
      bottom: "0%",
      right: "0%",
      top: "0%",
      height: "100%",
      position: "absolute",
      width: "100%",
    },
    vectorIcon2: {
      width: "17.83%",
      right: "82.17%",
      left: "0%",
      bottom: "0%",
      height: "100%",
      maxWidth: "100%",
      top: "0%",
    },
    toDoList1Traced: {
      width: "7.31%",
      right: "87.42%",
      left: "5.27%",
    },
    designChanges: {
      fontSize: 13,
      color: Color.colorGray,
      left: "0%",
      top: "0%",
    },
    group4: {
      right: "0%",
      width: "100%",
    },
    daysAgo: {
      width: "54.02%",
    },
    group3: {
      width: "74.84%",
      left: "25.16%",
    },
    group2: {
      width: "66%",
      right: "27.82%",
    },
    cardMediumItem: {
      height: "23.59%",
      width: "1.35%",
      top: "38.52%",
      right: "6.37%",
      bottom: "37.89%",
      left: "92.28%",
    },
    cardMedium: {
      top: 356,
    },
    vectorIcon3: {
      width: "25.77%",
      right: "74.23%",
      left: "0%",
      bottom: "0%",
      height: "100%",
      maxWidth: "100%",
      top: "0%",
    },
    toDoList1Traced1: {
      width: "10.57%",
      right: "81.82%",
      left: "7.61%",
    },
    daysAgo1: {
      width: "91.84%",
    },
    group6: {
      width: "63.64%",
      left: "36.36%",
    },
    group5: {
      width: "45.66%",
      right: "48.16%",
    },
    cardMedium1: {
      top: 526,
    },
    vectorIcon4: {
      width: "25.41%",
      right: "74.59%",
      left: "0%",
      bottom: "0%",
      height: "100%",
      maxWidth: "100%",
      top: "0%",
    },
    toDoList1Traced2: {
      width: "10.42%",
      right: "82.07%",
      left: "7.5%",
    },
    daysAgo2: {
      width: "89.84%",
    },
    group9: {
      width: "64.15%",
      left: "35.85%",
    },
    group8: {
      width: "46.3%",
      right: "47.52%",
    },
    cardMedium2: {
      top: 441,
    },
    vectorIcon5: {
      width: "27.19%",
      right: "72.81%",
      left: "0%",
      bottom: "0%",
      height: "100%",
      maxWidth: "100%",
      top: "0%",
    },
    toDoList1Traced3: {
      width: "11.15%",
      right: "80.82%",
      left: "8.03%",
    },
    group13: {
      width: "70.17%",
      right: "29.83%",
    },
    daysAgo3: {
      width: "100%",
    },
    group12: {
      width: "61.65%",
      left: "38.35%",
    },
    group11: {
      width: "43.29%",
      right: "50.53%",
    },
    cardMedium3: {
      top: 611,
    },
    arrowShortLeft: {
      top: 35,
      left: 27,
      width: 26,
      height: 26,
      position: "absolute",
      overflow: "hidden",
    },
    taskCalender: {
      backgroundColor: Color.colorGray,
      flex: 1,
      height: 800,
      overflow: "hidden",
      width: "100%",
    },
  });

  export default styles;